"""Build the ground model the down camera looks at: sim/models/ground/.

Default: a procedural landscape texture (irregular fields, tracks, trees and bushes) with detail at every
scale, so image motion can be measured from a few metres up to a few hundred metres.

With --aerial: the Wufeng orthophoto from scripts/fetch_aerial.py, at its true ground size.
That path needs rasterio, so run it on the host: `uv run python sim/scripts/make_ground.py --aerial`.

Usage: python3 sim/scripts/make_ground.py [--aerial [TIF]] [--size M] [--px N] [--if-missing]
"""
import argparse
from pathlib import Path

import cv2
import numpy as np

OUT = Path(__file__).resolve().parents[1] / "models" / "ground"
DEFAULT_TIF = Path(__file__).resolve().parents[2] / "data/raw/aerial/wufeng_2020-03-23_x4.tif"
MAX_PX = 8192  # longest texture side; larger textures are too slow for CPU rendering


def noise(rng: np.random.Generator, px: int, octaves: int = 10) -> np.ndarray:
    """Multi-scale value noise in [0, 1], one octave per doubling of feature size."""
    acc = np.zeros((px, px), np.float32)
    for o in range(octaves):
        cells = max(2, px >> (octaves - o))
        layer = rng.random((cells, cells), dtype=np.float32)
        acc += cv2.resize(layer, (px, px), interpolation=cv2.INTER_CUBIC) * 0.6 ** (octaves - 1 - o)
    acc -= acc.min()
    return acc / acc.max()


def procedural(px: int, seed: int) -> np.ndarray:
    rng = np.random.default_rng(seed)
    base = noise(rng, px)
    moisture = noise(rng, px)
    # Irregular fields: nearest of ~150 random seed points (Voronoi cells), computed coarse then upsampled
    lo = 512
    seeds = rng.random((150, 2)) * lo
    yy, xx = np.mgrid[0:lo, 0:lo]
    d2 = (xx[..., None] - seeds[:, 0]) ** 2 + (yy[..., None] - seeds[:, 1]) ** 2
    cells = cv2.resize(d2.argmin(-1).astype(np.uint16), (px, px), interpolation=cv2.INTER_NEAREST)
    palette = np.array([[60, 110, 50], [85, 130, 60], [120, 140, 70], [110, 95, 65], [70, 95, 45], [140, 130, 90]], np.float32)
    rgb = palette[rng.integers(0, len(palette), len(seeds))[cells]] * (0.6 + 0.8 * base[..., None])
    rgb[..., 1] += 30 * (moisture - 0.5)
    # Fine grain so low flight still sees texture
    rgb += (rng.random((px, px, 1), dtype=np.float32) - 0.5) * 40
    # Dirt tracks
    for _ in range(25):
        p0, p1 = rng.integers(0, px, 2), rng.integers(0, px, 2)
        cv2.line(rgb, tuple(map(int, p0)), tuple(map(int, p1)), (150, 135, 105), int(rng.integers(3, 9)))
    # Trees and bushes, 1 to 4 m across, denser where it is moist
    for _ in range(px * 6):
        x, y = rng.integers(0, px, 2)
        if moisture[y, x] < rng.random() * 0.9:
            continue
        r = int(rng.integers(2, 8))  # pixels: 0.5 to 2 m radius at the default 0.24 m/px
        shade = rng.uniform(0.5, 0.9)
        cv2.circle(rgb, (int(x) + r // 3, int(y) + r // 3), r, (25, 35, 20), -1)  # shadow
        cv2.circle(rgb, (int(x), int(y)), r, (40 * shade, 90 * shade, 35 * shade), -1)
    return np.clip(rgb, 0, 255).astype(np.uint8)  # RGB


def aerial(tif: Path) -> tuple[np.ndarray, float, float]:
    import rasterio

    with rasterio.open(tif) as src:
        img = np.moveaxis(src.read([1, 2, 3]), 0, -1)
        width_m = abs(src.transform.a) * src.width
        height_m = abs(src.transform.e) * src.height
    scale = min(1.0, MAX_PX / max(img.shape[:2]))
    if scale < 1:
        img = cv2.resize(img, None, fx=scale, fy=scale, interpolation=cv2.INTER_AREA)
    return img, width_m, height_m


MODEL_SDF = """<?xml version="1.0"?>
<!-- Generated by sim/scripts/make_ground.py ({source}). Image top is north (+Y), right is east (+X). -->
<sdf version="1.10">
  <model name="ground">
    <static>true</static>
    <link name="link">
      <collision name="collision">
        <geometry><plane><normal>0 0 1</normal><size>{w:.1f} {h:.1f}</size></plane></geometry>
      </collision>
      <visual name="visual">
        <geometry><plane><normal>0 0 1</normal><size>{w:.1f} {h:.1f}</size></plane></geometry>
        <material>
          <ambient>1 1 1 1</ambient><diffuse>1 1 1 1</diffuse><specular>0 0 0 1</specular>
          <pbr><metal>
            <albedo_map>model://ground/materials/textures/ground.jpg</albedo_map>
            <roughness>1.0</roughness><metalness>0.0</metalness>
          </metal></pbr>
        </material>
      </visual>
    </link>
  </model>
</sdf>
"""


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--aerial", nargs="?", const=DEFAULT_TIF, type=Path, help="use an orthophoto GeoTIFF")
    ap.add_argument("--size", type=float, default=1000.0, help="procedural ground side in metres")
    ap.add_argument("--px", type=int, default=4096, help="procedural texture side in pixels")
    ap.add_argument("--seed", type=int, default=7)
    ap.add_argument("--if-missing", action="store_true", help="do nothing if the ground already exists")
    args = ap.parse_args()

    texture = OUT / "materials" / "textures" / "ground.jpg"
    if args.if_missing and texture.exists():
        return
    if args.aerial:
        img, w, h = aerial(args.aerial)
        source = f"orthophoto {args.aerial.name}"
    else:
        img, w, h = procedural(min(args.px, MAX_PX), args.seed), args.size, args.size
        source = f"procedural, seed {args.seed}"

    texture.parent.mkdir(parents=True, exist_ok=True)
    cv2.imwrite(str(texture), cv2.cvtColor(img, cv2.COLOR_RGB2BGR), [cv2.IMWRITE_JPEG_QUALITY, 92])
    (OUT / "model.sdf").write_text(MODEL_SDF.format(source=source, w=w, h=h))
    (OUT / "model.config").write_text(
        '<?xml version="1.0"?>\n<model><name>ground</name><version>1.0</version>'
        '<sdf version="1.10">model.sdf</sdf></model>\n'
    )
    print(f"ground: {source}, {w:.0f} x {h:.0f} m, {img.shape[1]} x {img.shape[0]} px "
          f"({w / img.shape[1]:.2f} m/px) -> {OUT}")


if __name__ == "__main__":
    main()
