"""Build 3D trees around the flight area: sim/models/trees/.

Broadleaf trees (trunk and rounded crown) and conifers (trunk and cone), 6 to 18 m tall, in
clumps of woods with single trees between them. They stand on the flat ground, give the down
camera real height and parallax, and are solid. A clear patch is kept around the start point.

Usage: python3 sim/scripts/make_trees.py [--count N] [--area M] [--seed S] [--if-missing]
"""
import argparse
import math
from pathlib import Path

import numpy as np

OUT = Path(__file__).resolve().parents[1] / "models" / "trees"
VERSION = "1"  # bump when the trees change, so --if-missing rebuilds old copies
CLEAR_RADIUS = 12.0  # m kept free around the start point (0, 0)

BROADLEAF = """
      <visual name="t{i}_trunk">
        <pose>{x:.2f} {y:.2f} {th:.2f} 0 0 0</pose>
        <geometry><cylinder><radius>{tr:.2f}</radius><length>{tl:.2f}</length></cylinder></geometry>
        <material><ambient>{bark}</ambient><diffuse>{bark}</diffuse></material>
      </visual>
      <visual name="t{i}_crown">
        <pose>{x:.2f} {y:.2f} {cz:.2f} 0 0 {yaw:.2f}</pose>
        <geometry><ellipsoid><radii>{rx:.2f} {ry:.2f} {rz:.2f}</radii></ellipsoid></geometry>
        <material><ambient>{leaf}</ambient><diffuse>{leaf}</diffuse><specular>0.02 0.02 0.02 1</specular></material>
      </visual>
      <collision name="t{i}">
        <pose>{x:.2f} {y:.2f} {hh:.2f} 0 0 0</pose>
        <geometry><cylinder><radius>{cr:.2f}</radius><length>{h:.2f}</length></cylinder></geometry>
      </collision>"""

CONIFER = """
      <visual name="t{i}_trunk">
        <pose>{x:.2f} {y:.2f} {th:.2f} 0 0 0</pose>
        <geometry><cylinder><radius>{tr:.2f}</radius><length>{tl:.2f}</length></cylinder></geometry>
        <material><ambient>{bark}</ambient><diffuse>{bark}</diffuse></material>
      </visual>
      <visual name="t{i}_crown">
        <pose>{x:.2f} {y:.2f} {cz:.2f} 0 0 0</pose>
        <geometry><cone><radius>{rx:.2f}</radius><length>{cl:.2f}</length></cone></geometry>
        <material><ambient>{leaf}</ambient><diffuse>{leaf}</diffuse><specular>0.02 0.02 0.02 1</specular></material>
      </visual>
      <collision name="t{i}">
        <pose>{x:.2f} {y:.2f} {hh:.2f} 0 0 0</pose>
        <geometry><cylinder><radius>{cr:.2f}</radius><length>{h:.2f}</length></cylinder></geometry>
      </collision>"""

MODEL = """<?xml version="1.0"?>
<!-- Generated by sim/scripts/make_trees.py ({count} trees, seed {seed}). -->
<sdf version="1.11">
  <model name="trees">
    <static>true</static>
    <link name="link">{body}
    </link>
  </model>
</sdf>
"""


def rgba(r, g, b):
    return f"{r:.3f} {g:.3f} {b:.3f} 1"


def positions(rng, count, area):
    """About two thirds of the trees in clumps (woods), the rest scattered."""
    half = area / 2
    pts = []
    clumps = rng.uniform(-half, half, (max(1, count // 40), 2))
    while len(pts) < count:
        if rng.random() < 0.65:
            c = clumps[rng.integers(len(clumps))]
            p = c + rng.normal(0, 14, 2)
        else:
            p = rng.uniform(-half, half, 2)
        if abs(p[0]) > half or abs(p[1]) > half or math.hypot(*p) < CLEAR_RADIUS:
            continue
        # keep trunks at least 3 m apart
        if pts and min(math.hypot(p[0] - q[0], p[1] - q[1]) for q in pts[-200:]) < 3.0:
            continue
        pts.append(p)
    return pts


def build(count, area, seed):
    rng = np.random.default_rng(seed)
    body = []
    for i, (x, y) in enumerate(positions(rng, count, area)):
        bark = rgba(*(np.array([0.30, 0.22, 0.15]) * rng.uniform(0.8, 1.1)))
        if rng.random() < 0.65:  # broadleaf
            h = rng.uniform(6, 14)
            rz = h * rng.uniform(0.28, 0.36)  # crown half-height
            rx = rz * rng.uniform(0.9, 1.3)
            ry = rx * rng.uniform(0.85, 1.15)
            tl = h - rz  # trunk reaches the crown centre
            g = rng.uniform(0.75, 1.15)
            leaf = rgba(0.20 * g, 0.40 * g, 0.14 * g)
            body.append(BROADLEAF.format(i=i, x=x, y=y, th=tl / 2, tr=0.12 + 0.015 * h, tl=tl,
                                         cz=h - rz, rx=rx, ry=ry, rz=rz, yaw=rng.uniform(0, math.pi),
                                         bark=bark, leaf=leaf, hh=h / 2, h=h, cr=0.8 * min(rx, ry)))
        else:  # conifer
            h = rng.uniform(9, 18)
            cl = h * rng.uniform(0.7, 0.85)  # cone length
            rx = cl * rng.uniform(0.2, 0.26)
            tl = h - cl + 0.5
            g = rng.uniform(0.75, 1.1)
            leaf = rgba(0.12 * g, 0.30 * g, 0.16 * g)
            body.append(CONIFER.format(i=i, x=x, y=y, th=tl / 2, tr=0.10 + 0.012 * h, tl=tl,
                                       cz=h - cl / 2, rx=rx, cl=cl, bark=bark, leaf=leaf,
                                       hh=h / 2, h=h, cr=0.6 * rx))
    return MODEL.format(count=count, seed=seed, body="".join(body))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--count", type=int, default=400)
    ap.add_argument("--area", type=float, default=400.0, help="side of the square they stand in, m")
    ap.add_argument("--seed", type=int, default=11)
    ap.add_argument("--if-missing", action="store_true",
                    help="do nothing if this version of the trees already exists")
    args = ap.parse_args()

    stamp = OUT / "VERSION"
    if args.if_missing and stamp.exists() and stamp.read_text().strip() == VERSION:
        return
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "model.sdf").write_text(build(args.count, args.area, args.seed))
    (OUT / "model.config").write_text(
        '<?xml version="1.0"?>\n<model><name>trees</name><version>1.0</version>'
        '<sdf version="1.11">model.sdf</sdf></model>\n'
    )
    stamp.write_text(VERSION + "\n")
    print(f"trees: {args.count} in {args.area:.0f} x {args.area:.0f} m, seed {args.seed} -> {OUT}")


if __name__ == "__main__":
    main()
